App\Entity\Location:
  properties:
    city:
      - NotBlank:
          message: "City is required."
          groups: ['create', 'edit']
      - Length:
          max: 255
          maxMessage: "City name cannot exceed {{ limit }} characters."
          groups: ['create', 'edit']
    country:
      - NotBlank:
          message: "Country code is required."
          groups: ['create', 'edit']
      - Length:
          min: 2
          max: 2
          exactMessage: "Country code must be exactly {{ limit }} characters."
          groups: ['create', 'edit']
    latitude:
      - NotBlank:
          message: "Latitude is required."
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          notInRangeMessage: "Latitude must be between {{ min }} and {{ max }}."
          groups: ['create', 'edit']
    longitude:
      - NotBlank:
          message: "Longitude is required."
          groups: ['create', 'edit']
      - Range:
          min: -180
          max: 180
          notInRangeMessage: "Longitude must be between {{ min }} and {{ max }}."
          groups: ['create', 'edit']
